name: Feature Request
description: Suggest a feature
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the feature
      placeholder: What feature would you like to see?
    validations:
      required: true
  
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe the problem this feature would solve
      placeholder: |
        I'm always frustrated when...
        This would help me...
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered
      placeholder: Describe alternatives you've tried or considered
